[package]
name = "tako"
version = "0.1.0"
authors = ["J Pratt <jp10010101010000@gmail.com>"]
edition = "2018"
include = ["src/**/*", "LICENSE.md", "README.md"]

[features]
bench = [ "criterion" ]
default = []

[lib]
name = "takolib"
path = "src/lib.rs"

[[bin]]
name = "tako"
path = "src/main.rs"

[[bench]]
name = "tako_bench"
harness = false

[dependencies]
salsa = "0.15.0"
thiserror = "1.0.20"
derivative = "2.1.1"
rustyline = "6.3.0"
directories = "3.0"
termcolor = "1.1"
bitvec = "0.20"
criterion = { version = "0.3", optional = true }

[dev-dependencies]
pretty_assertions = "0.6.1"
rand = "0.7.3"

[profile.test]
opt-level = 3

[profile.release]
debug = true
