[package]
name = "tako"
version = "0.1.0"
authors = ["Joshua Pratt <jp10010101010000@gmail.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
salsa = "0.15.0"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
