[package]
name = "tako"
version = "0.1.0"
authors = ["Joshua Pratt <jp10010101010000@gmail.com>"]
edition = "2018"

[lib]
name = "takolib"
path = "src/lib.rs"

[[bin]]
name = "tako"
path = "src/main.rs"

[[bench]]
name = "tako_bench"
harness = false

[dependencies]
salsa = "0.15.0"
thiserror = "1.0.20"
derivative = "2.1.1"
rand = "0.7.3"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3"

[profile.test]
opt-level = 3
