# ~/.circleci/config.yml
version: 2
jobs:
  build_project:
    docker:
      - image: haskell:8.6.3
    parallelism: 1
    steps:
      - run: export TERM='Readline'
      # Ensure that we have git & ssh
      - run: apt-get update
      - run: apt-get install -y curl git ssh

      # Git checkout
      - checkout
      # Dependency installation (with caching)
      - restore_cache:
          keys:
            - cabal_packages-{{ .Branch }}-{{ checksum "tako.cabal" }}
            - cabal_packages-{{ .Branch }}-
            - cabal_packages-
            # Install dependencies fresh if we change the dependencies or compilation options to ensure
            # that they are 'mostly' stateless
      - run: cabal update

      # Run any builds and tests
      - run: cabal new-test
      - save_cache:
          key: cabal_packages-{{ .Branch }}-{{ checksum "tako.cabal" }}
          paths:
            - "~/.cabal/"
            - "dist/"
            - "dist-newstyle/"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
