# ~/.circleci/config.yml
version: 2
jobs:
  build_test:
    docker:
      - image: "debian:stretch"
    parallelism: 1
    steps:
      - run: export TERM='Readline'
      - run:
          name: Apt update
          command: 'apt-get update'
      - run:
          name: Installing SUDO
          command: 'apt-get install -y sudo'
      - run:
          name: Installing GCC
          command: 'apt-get install -y gcc g++'
      - run:
          name: Installing GIT
          command: 'apt-get install -y git'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get install -y cmake'
      - restore_cache:
          keys:
            - build_artifacts-{{ .Branch }}-{{ checksum "src/CMakeLists.txt" }}
            - build_artifacts-{{ .Branch }}-
            - build_artifacts-
      - checkout
      - run: git submodule init 
      - run: git submodule update
      - run:
          name: Building tako
          command: make build/tako
      - run:
          name: Building tests
          command: make build/takoTest
      - save_cache:
          key: build_artifacts-{{ .Branch }}-{{ checksum "src/CMakeLists.txt" }}
          paths:
            - "build/"
      - run:
          name: Running tests
          command: make test

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
