# ~/.circleci/config.yml
version: 2
jobs:
  build_test:
    docker:
      - image: "debian:stretch"
    parallelism: 1
    steps:
      - checkout
      - run: export TERM='Readline'
      - run:
        name: Installing SUDO
        command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
        name: Installing GCC
        command: 'apt-get update && apt-get install -y gcc g++'
      - run:
        name: Install CMAKE
        command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
        name: Building tako
        command: make build/tako
      - run:
        name: Building tests
        command: make build/test
      - run:
        name: Running tests
        command: make test

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
