version: 2
jobs:
  build_project:
    docker:
      - image: haskell:8.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - cabal_packages-{{ checksum "Htriple.cabal" }}
            # Install dependencies fresh if we change the dependencies or compilation options to ensure
            # that they are 'mostly' stateless
      - run: cabal update
      - run: cabal install --only-dependencies
      - run: cabal configure --enable-tests
      - run: cabal build
      - run: cabal test
      - save_cache:
          key: cabal_packages-{{ checksum "Htriple.cabal" }}
          paths:
            - ~/.cabal/
            - dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
