# ~/.circleci/config.yml
version: 2
jobs:
  build_project:
    docker:
      - image: circleci/rust:latest
    parallelism: 1
    steps:
      - run: export TERM='Readline'
      # Ensure that we have git & ssh
      - run: apt-get update
      - run: apt-get install -y curl git ssh

      # Git checkout
      - checkout
      - run: make -j 4
      # Run any builds and tests
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
