# ~/.circleci/config.yml
version: 2

references:
  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu
      command: |
        apt-get update -qy
        apt-get install -qy git cmake clang

  arch_deps: &arch_deps
    run:
      name: Install dependencies on Arch Linux
      command: |
        pacman -Syu --noconfirm base-devel git cmake clang

  update_submodules: &update_submodules
    run:
      name: Update git submodules
      command: |
        git submodule update --init --recursive

  build_with_gcc: &build_with_gcc
    run:
      name: Build with g++.
      command: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ../src
        make tako
        make takoTest
      no_output_timeout: 20m

  build_with_clang: &build_with_clang
      run:
        name: Build with clang++.
        command: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ ../src
          make tako
          make takoTest
        no_output_timeout: 20m

  test: &test
    run:
      name: Run unit tests
      command: |
        ./build/takoTest
    run:
      name: Run parser on example code
      command: |
        ./build/tako test.tako

jobs:
  test_arch_gcc:
    docker:
      - image: archlinux/base
    steps:
      - *arch_deps
      - checkout
      - *update_submodules
      - *build_with_gcc
      - *test

  test_arch_clang:
    docker:
      - image: archlinux/base
    steps:
      - *arch_deps
      - checkout
      - *update_submodules
      - *build_with_clang
      - *test

  test_ubuntu_gcc:
    docker:
      - image: ubuntu:latest
    steps:
      - *ubuntu_deps
      - checkout
      - *update_submodules
      - *build_with_gcc
      - *test

  test_ubuntu_clang:
    docker:
      - image: ubuntu:latest
    steps:
      - *ubuntu_deps
      - checkout
      - *update_submodules
      - *build_with_clang
      - *test

workflows:
  version: 2

  test_matrix: &test_matrix
    jobs:
      - test_archlinux_gcc
      - test_archlinux_clang
      - test_ubuntu_gcc
      - test_ubuntu_clang
