# ~/.circleci/config.yml
version: 2

references:
  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu
      command: |
        apt-get update -qy
        apt-get install -qy git clang g++-6 meson

  arch_deps: &arch_deps
    run:
      name: Install dependencies on Arch
      command: |
        pacman -Syu --noconfirm base-devel git openssh clang gcc meson

  update_submodules: &update_submodules
    run:
      name: Update git submodules
      command: |
        git submodule update --init --recursive

  build_with_gcc: &build_with_gcc
    run:
      name: Build with g++.
      command: |
        meson build
        ninja -C build
      no_output_timeout: 20m

  build_with_clang: &build_with_clang
      run:
        name: Build with clang++.
        command: |
          CC=clang CXX=clang++ meson build
          ninja -C build
        no_output_timeout: 20m

  unit_test: &unit_test
    run:
      name: Run unit tests
      command: |
        ninja -C build test

  example_test: &example_test
    run:
      name: Run parser on example code
      command: |
        ./build/tako test.tako

jobs:
  test_arch_gcc:
    docker:
      - image: archlinux/base
    steps:
      - *arch_deps
      - checkout
      - *update_submodules
      - *build_with_gcc
      - *unit_test
      - *example_test

  test_arch_clang:
    docker:
      - image: archlinux/base
    steps:
      - *arch_deps
      - checkout
      - *update_submodules
      - *build_with_clang
      - *unit_test
      - *example_test

  test_ubuntu_gcc:
    docker:
      - image: ubuntu:latest
    steps:
      - *ubuntu_deps
      - checkout
      - *update_submodules
      - *build_with_gcc
      - *unit_test
      - *example_test

  test_ubuntu_clang:
    docker:
      - image: ubuntu:latest
    steps:
      - *ubuntu_deps
      - checkout
      - *update_submodules
      - *build_with_clang
      - *unit_test
      - *example_test

workflows:
  version: 2

  test_matrix: &test_matrix
    jobs:
      # Not running gcc at the moment due to lack of c++17 support.
      # - test_arch_gcc
      # - test_ubuntu_gcc
      - test_arch_clang
      - test_ubuntu_clang
