version: 2
jobs:
  build_project:
    docker:
      - image: haskell:8.0.2
    steps:
      - checkout
      - run: cabal update
      - run: cabal install QuickCheck
      - run: cabal configure --enable-tests
      - run: cabal build
      - run: cabal test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
