# ~/.circleci/config.yml
version: 2
docker:
  - image: "debian:stretch"
parallelism: 1
jobs:
  build:
    steps:
      - checkout
      - run: export TERM='Readline'
      - run:
        name: Installing SUDO
        command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
        name: Installing GCC
        command: 'apt-get update && apt-get install -y gcc g++'
      - run:
        name: Install CMAKE
        command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
        name: Building tako
        command: make build/tako
      - run:
        name: Building tests
        command: make build/test

  test:
    steps:
      - run:
        name: Running tests
        command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
